-- diet-tracker: Supabase (Postgres) スキーマ
-- Supabaseダッシュボードの SQL Editor でこのファイルの内容をそのまま実行する。
-- ログイン認証なしで誰でも読み書きできる共有DBとして運用する前提のため、
-- RLSは有効にした上で「全操作を許可」するポリシーを付けている
-- (匿名キーがアプリのビルド成果物に埋め込まれて公開されるため、実質的な
-- アクセス制御はこのポリシーの範囲=ネットワーク到達可能な全員、になる)。

create table if not exists clients (
  id integer generated by default as identity primary key,
  name text not null,
  birthdate text,
  "heightCm" double precision,
  gender text,
  "activityLevel" text not null,
  "pfcPreset" text not null,
  "targetMonthlyWeightChangeKg" double precision,
  "targetWeightChangeKg" double precision,
  "targetPeriodMonths" double precision,
  "targetWeightKg" double precision,
  memo text,
  "createdAt" timestamptz not null default now()
);

create table if not exists measurements (
  id integer generated by default as identity primary key,
  "clientId" integer not null references clients(id) on delete cascade,
  "recordedAt" text not null,
  "weightKg" double precision,
  "bodyFatPct" double precision,
  "muscleMassKg" double precision,
  "visceralFatLevel" double precision,
  "bmrKcal" double precision,
  memo text
);
create index if not exists measurements_client_recorded_idx
  on measurements ("clientId", "recordedAt");

create table if not exists foods (
  id integer generated by default as identity primary key,
  category text not null,
  name text not null,
  "servingLabel" text not null,
  kcal double precision not null,
  "proteinG" double precision not null,
  "fatG" double precision not null,
  "carbG" double precision not null,
  unique (category, name)
);

create table if not exists "mealLogs" (
  id integer generated by default as identity primary key,
  "clientId" integer not null references clients(id) on delete cascade,
  "recordedAt" text not null,
  "mealType" text not null,
  "foodId" integer references foods(id) on delete set null,
  "foodName" text not null,
  quantity double precision not null,
  kcal double precision not null,
  "proteinG" double precision not null,
  "fatG" double precision not null,
  "carbG" double precision not null,
  memo text
);
create index if not exists meal_logs_client_recorded_idx
  on "mealLogs" ("clientId", "recordedAt");
create index if not exists meal_logs_food_idx on "mealLogs" ("foodId");

create table if not exists "usualMeals" (
  id integer generated by default as identity primary key,
  "clientId" integer not null references clients(id) on delete cascade,
  "mealType" text not null,
  "foodId" integer references foods(id) on delete set null,
  "foodName" text not null,
  quantity double precision not null,
  kcal double precision not null,
  "proteinG" double precision not null,
  "fatG" double precision not null,
  "carbG" double precision not null
);
create index if not exists usual_meals_client_idx on "usualMeals" ("clientId");
create index if not exists usual_meals_food_idx on "usualMeals" ("foodId");

create table if not exists exercises (
  id integer generated by default as identity primary key,
  category text not null,
  name text not null,
  mets double precision not null,
  unique (category, name)
);

create table if not exists "usualExercises" (
  id integer generated by default as identity primary key,
  "clientId" integer not null references clients(id) on delete cascade,
  "exerciseId" integer references exercises(id) on delete set null,
  "exerciseName" text not null,
  mets double precision not null,
  "durationMin" double precision not null,
  "frequencyPerWeek" double precision not null
);
create index if not exists usual_exercises_client_idx on "usualExercises" ("clientId");
create index if not exists usual_exercises_exercise_idx on "usualExercises" ("exerciseId");

create table if not exists "protocolChecks" (
  id integer generated by default as identity primary key,
  "clientId" integer not null references clients(id) on delete cascade,
  "recordedAt" text not null,
  "conditionId" text not null,
  results jsonb not null,
  memo text
);
create index if not exists protocol_checks_client_recorded_idx
  on "protocolChecks" ("clientId", "recordedAt");

-- RLS: 認証なしで誰でも読み書きできるようにする(要件により、個別ログインは設けない)。
alter table clients enable row level security;
alter table measurements enable row level security;
alter table foods enable row level security;
alter table "mealLogs" enable row level security;
alter table "usualMeals" enable row level security;
alter table exercises enable row level security;
alter table "usualExercises" enable row level security;
alter table "protocolChecks" enable row level security;

drop policy if exists "public full access" on clients;
create policy "public full access" on clients for all using (true) with check (true);

drop policy if exists "public full access" on measurements;
create policy "public full access" on measurements for all using (true) with check (true);

drop policy if exists "public full access" on foods;
create policy "public full access" on foods for all using (true) with check (true);

drop policy if exists "public full access" on "mealLogs";
create policy "public full access" on "mealLogs" for all using (true) with check (true);

drop policy if exists "public full access" on "usualMeals";
create policy "public full access" on "usualMeals" for all using (true) with check (true);

drop policy if exists "public full access" on exercises;
create policy "public full access" on exercises for all using (true) with check (true);

drop policy if exists "public full access" on "usualExercises";
create policy "public full access" on "usualExercises" for all using (true) with check (true);

drop policy if exists "public full access" on "protocolChecks";
create policy "public full access" on "protocolChecks" for all using (true) with check (true);

-- Realtime(端末間のリアルタイム同期)用に、全テーブルをpublicationへ追加する。
-- 既に追加済みの場合はエラーになるため、存在確認してから追加する。
do $$
declare
  t text;
begin
  foreach t in array array['clients', 'measurements', 'foods', 'mealLogs', 'usualMeals', 'exercises', 'usualExercises', 'protocolChecks']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table %I', t);
    end if;
  end loop;
end $$;

-- データ管理画面(/data)からのインポート機能用: bulkインポートでidを明示指定して
-- 挿入した後、次回以降のauto-increment(identity)がその最大id以下から再開して
-- 重複してしまわないよう、各テーブルのシーケンスを現在の最大idに合わせ直す。
-- 匿名ロールにテーブルへの直接のシーケンス操作権限は与えていないため、
-- security definerな関数経由で実行する。
create or replace function reset_id_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
begin
  foreach t in array array['clients', 'measurements', 'foods', 'mealLogs', 'usualMeals', 'exercises', 'usualExercises', 'protocolChecks']
  loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from %I), 1))',
      quote_ident(t), t
    );
  end loop;
end;
$$;

grant execute on function reset_id_sequences() to anon, authenticated;

-- データ管理画面(/data)の「インポート」用: 全テーブルの削除→再投入を
-- 1回の関数呼び出し(=1トランザクション)にまとめる。クライアント側で
-- 複数回のAPI呼び出しに分けていた場合、途中の1回が失敗すると一部のテーブルだけ
-- 空になったまま残ってしまう(共有DBなので他端末にもその不完全な状態が
-- 見えてしまう)。関数内で例外が起きれば呼び出し全体が自動的にロールバックされる
-- ため、この不整合を防げる。
create or replace function import_all_data(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from "protocolChecks";
  delete from "usualExercises";
  delete from "usualMeals";
  delete from "mealLogs";
  delete from measurements;
  delete from clients;
  delete from foods;
  delete from exercises;

  insert into clients (
    id, name, birthdate, "heightCm", gender, "activityLevel", "pfcPreset",
    "targetMonthlyWeightChangeKg", "targetWeightChangeKg", "targetPeriodMonths",
    "targetWeightKg", memo, "createdAt"
  )
  select
    id, name, birthdate, "heightCm", gender, "activityLevel", "pfcPreset",
    "targetMonthlyWeightChangeKg", "targetWeightChangeKg", "targetPeriodMonths",
    "targetWeightKg", memo, "createdAt"
  from jsonb_to_recordset(payload->'clients') as t(
    id integer, name text, birthdate text, "heightCm" double precision, gender text,
    "activityLevel" text, "pfcPreset" text,
    "targetMonthlyWeightChangeKg" double precision, "targetWeightChangeKg" double precision,
    "targetPeriodMonths" double precision, "targetWeightKg" double precision,
    memo text, "createdAt" timestamptz
  );

  insert into foods (id, category, name, "servingLabel", kcal, "proteinG", "fatG", "carbG")
  select id, category, name, "servingLabel", kcal, "proteinG", "fatG", "carbG"
  from jsonb_to_recordset(payload->'foods') as t(
    id integer, category text, name text, "servingLabel" text, kcal double precision,
    "proteinG" double precision, "fatG" double precision, "carbG" double precision
  );

  insert into exercises (id, category, name, mets)
  select id, category, name, mets
  from jsonb_to_recordset(payload->'exercises') as t(
    id integer, category text, name text, mets double precision
  );

  insert into measurements (
    id, "clientId", "recordedAt", "weightKg", "bodyFatPct", "muscleMassKg",
    "visceralFatLevel", "bmrKcal", memo
  )
  select
    id, "clientId", "recordedAt", "weightKg", "bodyFatPct", "muscleMassKg",
    "visceralFatLevel", "bmrKcal", memo
  from jsonb_to_recordset(payload->'measurements') as t(
    id integer, "clientId" integer, "recordedAt" text, "weightKg" double precision,
    "bodyFatPct" double precision, "muscleMassKg" double precision,
    "visceralFatLevel" double precision, "bmrKcal" double precision, memo text
  );

  insert into "mealLogs" (
    id, "clientId", "recordedAt", "mealType", "foodId", "foodName", quantity,
    kcal, "proteinG", "fatG", "carbG", memo
  )
  select
    id, "clientId", "recordedAt", "mealType", "foodId", "foodName", quantity,
    kcal, "proteinG", "fatG", "carbG", memo
  from jsonb_to_recordset(payload->'mealLogs') as t(
    id integer, "clientId" integer, "recordedAt" text, "mealType" text,
    "foodId" integer, "foodName" text, quantity double precision, kcal double precision,
    "proteinG" double precision, "fatG" double precision, "carbG" double precision, memo text
  );

  insert into "usualMeals" (
    id, "clientId", "mealType", "foodId", "foodName", quantity, kcal, "proteinG", "fatG", "carbG"
  )
  select
    id, "clientId", "mealType", "foodId", "foodName", quantity, kcal, "proteinG", "fatG", "carbG"
  from jsonb_to_recordset(payload->'usualMeals') as t(
    id integer, "clientId" integer, "mealType" text, "foodId" integer, "foodName" text,
    quantity double precision, kcal double precision, "proteinG" double precision,
    "fatG" double precision, "carbG" double precision
  );

  insert into "usualExercises" (
    id, "clientId", "exerciseId", "exerciseName", mets, "durationMin", "frequencyPerWeek"
  )
  select
    id, "clientId", "exerciseId", "exerciseName", mets, "durationMin", "frequencyPerWeek"
  from jsonb_to_recordset(payload->'usualExercises') as t(
    id integer, "clientId" integer, "exerciseId" integer, "exerciseName" text,
    mets double precision, "durationMin" double precision, "frequencyPerWeek" double precision
  );

  insert into "protocolChecks" (id, "clientId", "recordedAt", "conditionId", results, memo)
  select id, "clientId", "recordedAt", "conditionId", results, memo
  from jsonb_to_recordset(payload->'protocolChecks') as t(
    id integer, "clientId" integer, "recordedAt" text, "conditionId" text,
    results jsonb, memo text
  );

  perform reset_id_sequences();
end;
$$;

grant execute on function import_all_data(jsonb) to anon, authenticated;

-- 運動マスタの初期データ(厚生労働省「健康づくりのための身体活動・運動ガイド2023」)。
-- 旧Dexie版でブラウザの初回起動時に自動投入していたものと同じ内容。
insert into exercises (category, name, mets) values
  ('生活活動', '普通歩行(平地、約4.0km/時、犬を連れて)', 3.0),
  ('生活活動', '電動アシスト付き自転車に乗る', 3.0),
  ('生活活動', 'カーペット掃き・フロア掃き・掃除機', 3.3),
  ('生活活動', '歩行(平地、約4.5〜5.1km/時、散歩など)', 3.5),
  ('生活活動', '楽に自転車に乗る(8.9km/時)', 3.5),
  ('生活活動', '自転車に乗る(16km/時未満、通勤)', 4.0),
  ('生活活動', '階段を上る(ゆっくり)', 4.0),
  ('生活活動', 'やや速歩(平地、やや速めに、約5.6km/時)', 4.3),
  ('生活活動', 'かなり速歩(平地、速く、約6.4km/時)', 5.0),
  ('生活活動', 'こどもと遊ぶ(歩く/走る、活発に)', 5.8),
  ('生活活動', '農作業(干し草をまとめる、納屋の掃除)', 7.8),
  ('生活活動', '階段を上る(速く)', 8.8),
  ('運動', 'ストレッチング', 2.3),
  ('運動', 'ヨガ・ビリヤード', 2.5),
  ('運動', 'ボウリング・バレーボール・社交ダンス', 3.0),
  ('運動', '太極拳・ピラティス', 3.0),
  ('運動', '自転車エルゴメーター(30〜50ワット)', 3.5),
  ('運動', '体操(家で、軽・中等度)', 3.5),
  ('運動', 'ゴルフ(手引きカートを使って)', 3.5),
  ('運動', 'ほどほどの強度で行う筋トレ(腕立て伏せ・腹筋運動)', 3.8),
  ('運動', '卓球', 4.0),
  ('運動', 'ラジオ体操第1', 4.0),
  ('運動', 'テニス(ダブルス)', 4.5),
  ('運動', '水中歩行(中等度)', 4.5),
  ('運動', '水泳(ゆっくりとした背泳)', 4.8),
  ('運動', '野球・ソフトボール', 5.0),
  ('運動', '筋トレ(スクワット)', 5.0),
  ('運動', '水泳(ゆっくりとした平泳ぎ)', 5.3),
  ('運動', 'スキー・アクアビクス', 5.3),
  ('運動', 'バドミントン', 5.5),
  ('運動', 'ゆっくりとしたジョギング', 6.0),
  ('運動', 'ウェイトトレーニング(高強度)', 6.0),
  ('運動', 'バスケットボール', 6.0),
  ('運動', '山を登る(軽装)', 6.5),
  ('運動', '自転車エルゴメーター(90〜100ワット)', 6.8),
  ('運動', 'ジョギング', 7.0),
  ('運動', 'サッカー・スキー・スケート・ハンドボール', 7.0),
  ('運動', 'エアロビクス', 7.3),
  ('運動', 'テニス(シングルス)', 7.3),
  ('運動', 'サイクリング(約20km/時)', 8.0),
  ('運動', '激しい強度で行う筋トレ(腕立て伏せ・腹筋運動)', 8.0),
  ('運動', 'ランニング(約8.0km/時)', 8.3),
  ('運動', '水泳(クロール、ふつうの速さ)', 8.3),
  ('運動', 'ランニング(約9.7km/時)', 9.8),
  ('運動', '水泳(クロール、速い)', 10.0),
  ('運動', '武道・武術(柔道・空手など)', 10.3),
  ('運動', 'ランニング(約11.3km/時)', 11.0)
on conflict (category, name) do nothing;
